spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_system
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxd.jqstudentgrowthtrackingsystem.model
server:
  port: 8087
