spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_system
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxd.jqstudentgrowthtrackingsystem.model
server:
  port: 8087

  servlet: #配置文件上传下载
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB #设置单个文件上传的数据大小
      max-request-size: 100MB #设置总上传的数据大小